#===========================================================================
# allowed DPIs
#===========================================================================
dpis:
#  - 254
#  - 190
#  - 127
#  - 56
  - 72
#  - 144
#  - 190
#  - 254
#
#  - 300
globalParallelFetches: 1
maxSvgWidth: 2048
maxSvgHeight: 2048
integerSvg: false
reloadConfig: false
#===========================================================================
# allowed Formats
#===========================================================================
# '*' means any formats
formats: ['*']

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 10000
  - 25000
  - 50000
  - 100000
  - 250000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 8000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: 127.0.0.1
    port: 80
  - !ipMatch
    ip: 127.0.0.1
    port: 8080
#  - !ipMatch
#    ip: 202.27.242.222
#    mask: 255.255.255.255
#    port: 80
#  - !ipMatch
#    ip: 202.27.242.222
#    mask: 255.255.255.255
#    port: 8080
  - !ipMatch
    ip: basemap-web.zen.landcareresearch.co.nz
    mask: 255.255.255.255
    port: 80
  - !ipMatch
    ip: maps-a.zen.landcareresearch.co.nz
    mask: 255.255.255.255
    port: 80
  - !ipMatch
    ip: maps-b.zen.landcareresearch.co.nz
    mask: 255.255.255.255
    port: 80
#    port: 80
#  - !dnsMatch
#    host: basemap-web.zen.landcareresearch.co.nz
#    mask: 255.255.255.255
#    port: 80
#  - !dnsMatch
#    host: ebop-web.zen.landcareresearch.co.nz
#    mask: 255.255.255.255
#    port: 8080

# the default fileName for the files downloaded from the servlet
outputFilename: Landcare_Print

layouts:
  #===========================================================================
  A4 Portrait:
  #===========================================================================
    # override the default outputFileName defined above
    outputFilename: 'OurEnv-${now yyyyMMdd-HHmmss}'
    mainPage:
      backgroundPdf: /opt/print/print_templates/print_template_A4_portrait_env.pdf
      rotation: false
      pageSize: A4
      header:
        height: 50
        items:
          - !columns
            absoluteX: -21
            absoluteY: 805
            width: 632
            items:
              - !text
                font: Arial
                fontSize: 15
                align: center
                text: '${mapTitle}'
      items:
        - !map
          absoluteX: 31
          absoluteY: 777
          width: 530
          height: 647
        - !columns
          absoluteX: 225.2
          absoluteY: 105
          width: 150
          items:
            - !scalebar
              maxSize: 150
              type: bar_sub
              intervals: 4
              units: m
              barSize: 3
              lineWidth: 0.5
              fontSize: 7
              labelDistance: 4
        - !columns
          absoluteX: 222
          absoluteY: 121
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Scale: ${scaleName}'
        - !columns
          absoluteX: 426.5
          absoluteY: 42
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Printed: ${now HH:mm:ss a EEE, d MMM yyyy}'
#        - !columns
#          #absoluteX: 225
#          absoluteX: 0
#          absoluteY: 120
#	  #190
#          #width: 350
#          width: 842
#          items:
#            - !text
#              align: center
#              text: '${comment}'
    lastPage:
      backgroundPdf: /opt/print/print_templates/print_template_A4_portrait_env_legend.pdf
      pageSize: A4
      items:
        - !columns
          absoluteX: 80
          absoluteY: 745
          width: 450
          items:
            - !text
              align: left
              font: Arial
              fontSize: 16
              text: 'Legend'
        - !columns
          absoluteX: 80
          absoluteY: 715
          width: 450
          items:
            - !legends
              maxHeight: 100
              inline: true
              backgroundColor: #FFFFFF
              maxIconWidth: 20
              maxIconHeight: 20
              classIndentation: 0
              layerSpace: 25
              #classSpace: 10
              classSpace: 20
              layerFont: Arial
              layerFontSize: 14
              classFont: Arial
              classFontSize: 12
              fontEncoding: Cp1252
#      footer:
#        height: 30
#        items:
#          - !columns
#            items:
#              - !text
#                align: right
#                text: 'Page ${pageNum}'
  #===========================================================================
  A4 Landscape:
  #===========================================================================
    # override the default outputFileName defined above
    outputFilename: 'OurEnv-${now yyyyMMdd-HHmmss}'
    #outputFilename: A4_Landscape
    mainPage:
      backgroundPdf: /opt/print/print_templates/print_template_A4_landscape_env.pdf
      rotation: false
      pageSize: A4
      landscape: true
      header:
        height: 50
        items:
          - !columns
            absoluteX: 0
            #absoluteY: 815
            absoluteY: 570
            #width: 632
            width: 842
            items:
              - !text
                font: Arial
                fontSize: 15
                align: center
                text: '${mapTitle}'
      items:
        - !map
          absoluteX: 31.5
          #absoluteY: 393
          absoluteY: 543
          #width: 530
          width: 778
          #height: 400
          height: 434
        - !columns
          #absoluteX: 275
          absoluteX: 326
          absoluteY: 86
          width: 200
          items:
            - !scalebar
              maxSize: 200
              type: bar_sub
              intervals: 4
              units: m
              barSize: 3
              lineWidth: 0.5
              fontSize: 7
              labelDistance: 4
        - !columns
          absoluteX: 345
          absoluteY: 102
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Scale: ${scaleName}'
        - !columns
          absoluteX: 672
          absoluteY: 35.5
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Printed: ${now HH:mm:ss a EEE, d MMM yyyy}'
#        - !columns
#          #absoluteX: 225
#          absoluteX: 0
#          absoluteY: 120
#	  #190
#          #width: 350
#          width: 842
#          items:
#            - !text
#              align: center
#              text: '${comment}'
    lastPage:
      backgroundPdf: /opt/print/print_templates/print_template_A4_landscape_env_legend.pdf
      pageSize: A4
      landscape: true
      items:
        - !columns
          absoluteX: 112
          absoluteY: 505
          width: 450
          items:
            - !text
              align: left
              font: Arial
              fontSize: 16
              text: 'Legend'
        - !columns
          absoluteX: 112
          absoluteY: 475
          #width: 450
          width: 600
          items:
            - !legends
              horizontalAlignment: left
              #horizontalAlignment: right
              maxHeight: 280
              maxWidth: 200
              #inline: true
              inline: true
              backgroundColor: #FFFFFF
              iconPadding: 3 0 0 0
              textPadding: 0 0 0 5
              maxIconWidth: 20
              maxIconHeight: 20
              classIndentation: 20
              layerSpace: 25
              classSpace: 10
              layerFont: Arial
              layerFontSize: 14
              classFont: Arial
              classFontSize: 12
              fontEncoding: Cp1252
#      footer:
#        height: 30
#        items:
#          - !columns
#            items:
#              - !text
#                align: right
#                text: 'Page ${pageNum}'
  #===========================================================================
  A3 Portrait:
  #===========================================================================
    # override the default outputFileName defined above
    outputFilename: 'OurEnv-${now yyyyMMdd-HHmmss}'
    #outputFilename: A3_Portrait
    mainPage:
      backgroundPdf: /opt/print/print_templates/print_template_A3_portrait_env.pdf
      rotation: false
      pageSize: A3
      header:
        height: 50
        items:
          - !columns
            absoluteX: 100
            absoluteY: 1135
            width: 632
            items:
              - !text
                font: Arial
                fontSize: 20
                align: center
                text: '${mapTitle}'
      items:
        - !map
          absoluteX: 35.5
          absoluteY: 1097.5
          width: 770.8
          height: 919.5
        - !columns
          absoluteX: 326
          absoluteY: 140
          width: 200
          items:
            - !scalebar
              maxSize: 200
              type: bar_sub
              intervals: 4
              units: m
              barSize: 3
              lineWidth: 0.5
              fontSize: 9
              labelDistance: 4
        - !columns
          absoluteX: 345
          absoluteY: 161.5
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 9
              text: 'Scale: ${scaleName}'
        - !columns
          absoluteX: 672
          absoluteY: 45
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Printed: ${now HH:mm:ss a EEE, d MMM yyyy}'
#        - !columns
#          #absoluteX: 225
#          absoluteX: 0
#          absoluteY: 120
#	  #190
#          #width: 350
#          width: 842
#          items:
#            - !text
#              align: center
#              text: '${comment}'
#        - !columns
#          absoluteX: 630
#          absoluteY: 1070
#          width: 125
#          items:
#            - !legends
#              #backgroundColor: #727A3E
#              backgroundColor: #FFFFFF
#              maxIconWidth: 10
#              maxIconHeight: 100
#              classIndentation: 0
#              layerSpace: 5
#              classSpace: 2
#              layerFont: Arial
#              layerFontSize: 0
#              classFont: Arial
#              classFontSize: 8
#              fontEncoding: Cp1252
    lastPage:
      backgroundPdf: /opt/print/print_templates/print_template_A3_portrait_env_legend.pdf
      pageSize: A3
      items:
        - !columns
          absoluteX: 110
          absoluteY: 1040
          width: 450
          items:
            - !text
              align: left
              font: Arial
              fontSize: 22
              text: 'Legend'
        - !columns
          absoluteX: 110
          absoluteY: 1000
          width: 450
          items:
            - !legends
              backgroundColor: #FFFFFF
              maxIconWidth: 30
              maxIconHeight: 30
              classIndentation: 0
              layerSpace: 30
              classSpace: 15
              layerFont: Arial
              layerFontSize: 20
              classFont: Arial
              classFontSize: 18
              fontEncoding: Cp1252
#      footer:
#        height: 30
#        items:
#          - !columns
#            items:
#              - !text
#                align: right
#                text: 'Page ${pageNum}'
  #===========================================================================
  A3 Landscape:
  #===========================================================================
    # override the default outputFileName defined above
    outputFilename: 'OurEnv-${now yyyyMMdd-HHmmss}'
    #outputFilename: A3_Landscape
    mainPage:
      backgroundPdf: /opt/print/print_templates/print_template_A3_landscape_env.pdf
      rotation: false
      pageSize: A3
      landscape: true
      header:
        height: 50
        items:
          - !columns
            absoluteX: 170
            absoluteY: 800
            width: 842
            items:
              - !text
                font: Arial
                fontSize: 25
                align: center
                text: '${mapTitle}'
      items:
        - !map
          absoluteX: 49.8
          absoluteY: 762.1
          width: 1088.2
          height: 600
        - !columns
          absoluteX: 478
          absoluteY: 130
          width: 250
          items:
            - !scalebar
              maxSize: 250
              type: bar_sub
              intervals: 4
              units: m
              barSize: 4
              lineWidth: 0.5
              fontSize: 9
              labelDistance: 4
        - !columns
          absoluteX: 522
          absoluteY: 153
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 9
              text: 'Scale: ${scaleName}'
        - !columns
          absoluteX: 1000
          absoluteY: 62
          width: 150
          items:
            - !text
              align: center
              font: Arial
              fontSize: 7
              text: 'Printed: ${now HH:mm:ss a EEE, d MMM yyyy}'
#        - !columns
#          #absoluteX: 225
#          absoluteX: 0
#          absoluteY: 120
#	  #190
#          #width: 350
#          width: 842
#          items:
#            - !text
#              align: center
#              text: '${comment}'
    lastPage:
      backgroundPdf: /opt/print/print_templates/print_template_A3_landscape_env_legend.pdf
      pageSize: A3
      landscape: true
      items:
        - !columns
          absoluteX: 110
          absoluteY: 720
          width: 450
          items:
            - !text
              align: left
              font: Arial
              fontSize: 22
              text: 'Legend'
        - !columns
          absoluteX: 110
          absoluteY: 680
          width: 450
          items:
            - !legends
              backgroundColor: #FFFFFF
              maxIconWidth: 30
              maxIconHeight: 30
              classIndentation: 0
              layerSpace: 30
              classSpace: 15
              layerFont: Arial
              layerFontSize: 20
              classFont: Arial
              classFontSize: 18
              fontEncoding: Cp1252

#      footer:
#        height: 30
#        items:
#          - !columns
#            items:
#              - !text
#                align: right
#                text: 'Page ${pageNum}'
